export const GET_RECIPES = "GET_RECIPES";
export const GET_NAME_RECIPES = "GET_NAME_RECIPES";
export const GET_DETAIL_RECIPE = "GET_DETAIL_RECIPE";
export const FILTER_BY_STATUS = "FILTER_BY_STATUS";
export const FILTER_ORDER = "FILTER_ORDER";
export const FILTER_HEALTHSCORE = "FILTER_HEALTHSCORE";
export const FILTER_CREATE = "FILTER_CREATE";
export const POST_RECIPE = "POST_RECIPE";
